# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/jammy64"
    #config.vm.box = "generic/centos9s"

    config.vm.provision :ansible do |ansible|
       ansible.playbook = "site.yml"
       #ansible.verbose = "vvvv"
       #ansible.host_key_checking = false
       #ansible.limit = 'all'
       ansible.become = true
       ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
       ansible.groups = {
          "myrole" => ["ipv6" ],
       }
    end

    config.vm.define "ipv6" do |ipv6|
        ipv6.vm.hostname = "ipv6"
    end

end
